source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'byebug'
gem 'capybara'
gem 'coffee-rails', '~> 4.1.0'
gem 'dragonfly'
gem 'fog'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'newrelic_rpm'
gem 'omniauth-facebook'
gem 'pg'
gem 'rack-cache'
gem 'sass-rails', '~> 5.0'
gem 'spring'
gem 'sqlite3'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'
gem 'web-console', '~> 2.0'
