source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'bcrypt-ruby'
gem 'capybara'
gem 'coffee-rails'
gem 'dragonfly'
gem 'fog'
gem 'jquery-rails'
gem 'newrelic_rpm'
gem 'omniauth-facebook'
gem 'pg'
gem 'rack-cache', :require => 'rack/cache'
gem 'sass-rails'
gem 'sqlite3'
gem 'twitter-bootstrap-rails'
gem 'uglifier'
